[package]
name = "quote-clipper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
srtlib = "0.1.7"
anyhow = { version = "1.0.75", features = ["backtrace"] }
regex = "1.10.2"
